<a href="https://colab.research.google.com/github/danielasberna/modulo14/blob/main/pratique_m14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

caminho_arquivo = '/content/drive/MyDrive/Colab/CHURN_TELECON_MOD08_TAREFA.csv'

df = pd.read_csv(caminho_arquivo, delimiter = ';')
df.head(10)

# Verificando tipos de dados
print(df.info())

# Exibir dados pr√©-processados
print(df.head())

# 2) A) DADOS FALTANTES
dados_faltantes = df.isnull().sum()
porcentagem_faltantes = (df.isnull().sum() / len(df)) * 100
df_faltantes = pd.DataFrame({'Quantidade Faltante': dados_faltantes,
                             'Porcentagem (%)': porcentagem_faltantes})

# Exibindo apenas as colunas com dados faltantes
df_faltantes = df_faltantes[df_faltantes['Quantidade Faltante'] > 0]

print("--- Dados Faltantes e suas Percentagens ---")
print(df_faltantes)

#2) B) Excluindo os faltantes apenas em 'Genero' e 'Churn' pois s√£o uma quantidade muito pequena de dados
df_cleaned = df.dropna(subset=['Genero', 'Churn'])
print(df_cleaned[['Genero', 'Churn']].isnull().sum())
df_cleaned.info()

#2) C) Para 'PhoneService' preenchemos com a categoria mais frequente
moda_phone = df_cleaned['PhoneService'].mode()[0]
df_cleaned['PhoneService'] = df_cleaned['PhoneService'].fillna(moda_phone)

# Para 'Pagamento_Mensal' preenchemos com a mediana
mediana_pag = df_cleaned['Pagamento_Mensal'].median()

print("Mediana:", mediana_pag)
df_cleaned['Pagamento_Mensal'] = df_cleaned['Pagamento_Mensal'].fillna(mediana_pag)
print(df_cleaned[['PhoneService', 'Pagamento_Mensal']].isnull().sum())

#3)
colunas_categoricas = [
    'Genero', 'Casado', 'Dependents', 'PhoneService',
    'Servico_Internet', 'Servico_Seguranca', 'Suporte_Tecnico',
    'StreamingTV', 'Tipo_Contrato', 'PaymentMethod', 'Churn'
]

for col in colunas_categoricas:
    df_cleaned[col] = df_cleaned[col].astype(str).str.strip().str.lower()

df_cleaned['Genero'] = df_cleaned['Genero'].replace({
    'm': 'masculino',
    'masc': 'masculino',
    'masculino': 'masculino',
    'f': 'feminino',
    'fem': 'feminino',
    'feminino': 'feminino'
})

df_cleaned['Casado'] = df_cleaned['Casado'].replace({
    'yes': 'sim',
    'y': 'sim',
    'no': 'nao',
    'n': 'nao'
})

#Conferindo valores √∫nicos para identificar se ainda existem inconsist√™ncias
for col in colunas_categoricas:
    print(f"{col}: {df_cleaned[col].unique()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerID          2500 non-null   object
 1   Genero              2488 non-null   object
 2   Idoso               2500 non-null   int64
 3   Casado              2500 non-null   object
 4   Dependents          2500 non-null   object
 5   Tempo_como_Cliente  2500 non-null   int64
 6   PhoneService        1018 non-null   object
 7   Servico_Internet    2500 non-null   object
 8   Servico_Seguranca   2500 non-null   object
 9   Suporte_Tecnico     2500 non-null   object
 10  StreamingTV         2500 non-null   object
 11  Tipo_Contrato       2500 non-null   object
 12  PaymentMethod       2500 non-null   object
 13  Pagamento_Mensal    2175 non-null   float64
 14  Total_Pago          2500 non-null   float64
 15  Churn               2495 non-null   object
dtypes: float64(2), int64(2), object(12)
memory usage: 312.6+ KB
None
   customerID  Genero  Idoso Casado Dependents  Tempo_como_Cliente  \
0  7590-VHVEG  Female      0    Yes         No                   1
1  5575-GNVDE    Male      0     No         No                  34
2  3668-QPYBK    Male      0     No         No                   2
3  7795-CFOCW    Male      0     No         No                  45
4  9237-HQITU     NaN      0     No         No                   2

  PhoneService Servico_Internet Servico_Seguranca Suporte_Tecnico StreamingTV  \
0           No              DSL                No              No          No
1          Yes              DSL               Yes              No          No
2          Yes              DSL               Yes              No          No
3           No              DSL               Yes             Yes          No
4          Yes      Fiber optic                No              No          No

    Tipo_Contrato              PaymentMethod  Pagamento_Mensal  Total_Pago  \
0  Month-to-month           Electronic check             29.85       29.85
1        One year               Mailed check             56.95     1889.50
2  Month-to-month               Mailed check             53.85      108.15
3        One year  Bank transfer (automatic)               NaN     1840.75
4  Month-to-month           Electronic check               NaN      151.65

  Churn
0    No
1    No
2   Yes
3    No
4   Yes
--- Dados Faltantes e suas Percentagens ---
                  Quantidade Faltante  Porcentagem (%)
Genero                             12             0.48
PhoneService                     1482            59.28
Pagamento_Mensal                  325            13.00
Churn                               5             0.20
Genero    0
Churn     0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 2488 entries, 0 to 2499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerID          2488 non-null   object
 1   Genero              2488 non-null   object
 2   Idoso               2488 non-null   int64
 3   Casado              2488 non-null   object
 4   Dependents          2488 non-null   object
 5   Tempo_como_Cliente  2488 non-null   int64
 6   PhoneService        1006 non-null   object
 7   Servico_Internet    2488 non-null   object
 8   Servico_Seguranca   2488 non-null   object
 9   Suporte_Tecnico     2488 non-null   object
 10  StreamingTV         2488 non-null   object
 11  Tipo_Contrato       2488 non-null   object
 12  PaymentMethod       2488 non-null   object
 13  Pagamento_Mensal    2175 non-null   float64
 14  Total_Pago          2488 non-null   float64
 15  Churn               2488 non-null   object
dtypes: float64(2), int64(2), object(12)
memory usage: 330.4+ KB
Mediana: 71.45
PhoneService        0
Pagamento_Mensal    0
dtype: int64

/tmp/ipython-input-1651053891.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['PhoneService'].fillna(moda_phone, inplace=True)
/tmp/ipython-input-1651053891.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['PhoneService'].fillna(moda_phone, inplace=True)
/tmp/ipython-input-1651053891.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['Pagamento_Mensal'].fillna(mediana_pag, inplace=True)
/tmp/ipython-input-1651053891.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Pagamento_Mensal'].fillna(mediana_pag, inplace=True)